### ISSUE TITLE
Add support for a way to ignore files

### ISSUE THREAD

**Issue by brikis98** [gruntwork-io/boilerplate#19]
`boilerplate` should support some way of specifying files in the template-folder to ignore while generating. Some of the ways ignores could be specified include:

* A new top-level section in `boilerplate.yml` called `ignores`. Example:

    ```yml
    variables:
      - name: Title
      - name: Description

    ignores:
      - .git
      - foo/bar/*
      - *.foo
    ```
* A `--ignore` flag that can be specified one or more times on the command-line. Example:

    ```
    boilerplate --template-folder /templates --output-folder /output --ignore '.git' --ignore 'foo/bar/*'
    ```
