### ISSUE TITLE
Add ability to use Go template syntax and variables within a template

### ISSUE THREAD

**Issue by brikis98** [gruntwork-io/boilerplate#21]
Example:

```yaml
variables:
  - name: BasePath

dependencies:
  - name: Foo
    template-folder: {{.BasePath}}/templates
    output-folder: {{.BasePath}}/output
```

Note how the `template-folder` and `output-folder` params of the `Foo` dependency use `{{.BasePath}}` to fill in the value entered for the `BasePath` variable.
