### ISSUE TITLE
Basic string interpolation fails in range block.

### ISSUE THREAD

**Issue by josh-padnick** [gruntwork-io/boilerplate#24]
Given:

**boilerplate.yml:**
```yaml
- name: Route53PublicHostedZones
   description: Enter the domain names (e.g. example.com) for which we should create a Route53 Public Hosted Zone
   type: list
   default:
     - bolste.com
     - bolste.red

- name: HostedZoneComment
    description: Enter the comment field for the Hosted Zone
    type: string
    default: Managed by Terraform
```

**main.tf:**
```
{{- range $index, $domainName := .Route53PublicHostedZones }}

resource "aws_route53_zone" "{{ $domainName | snakeCase }}" {
  name = "{{ $domainName }}"
  comment = "{{ .HostedZoneComment }}"
}
{{- end }}
```

I would expect this to work fine, but in fact, it fails with:

```
[boilerplate] 2016/12/22 14:36:42 Processing template ../../../patterns/infrastructure-live/global/route53/main.tf and writing to /repos/gruntwork-clients/bolste/infrastructure-live/global/route53/main.tf
template: ../../../patterns/infrastructure-live/global/route53/main.tf:25:15: executing "../../../patterns/infrastructure-live/global/route53/main.tf" at <.HostedZoneComment>: can't evaluate field HostedZoneComment in type string
```

Any thoughts on what's going on here?
